### ISSUE TITLE
Mobs in admin road claims cannot be attacked

### ISSUE THREAD

**Issue by Lemmmy** [SwitchCraftCC/issues#2]
### Describe the bug

You cannot attack (hostile) mobs in admin claims, or generally any claim you are not trusted in(?).

This is likely part of the protection that prevents you from breaking item frames or attacking pets/other passive mobs. As such, there should likely be multiple new claim flags, for example:

- entityDamage (false by default) - Allows damaging any non-living entities such as item frames
- animalDamage (false by default) - Allows damaging passive mobs (e.g. anything that inherits `MobEntity` but not `HostileEntity`)
- monsterDamage (true by default) - Allows damaging monsters (e.g. anything that inherits `HostileEntity`)

I believe that tags can (and should!) be used for this - we can datagen the mob lists by class inheritence and then make adjustments as needed. Data-driven everything!

Of course, future work would be granular claim flags, but I think that is out of scope for this report - the most frequent complaint right now is that you can't defend yourself on a spawn road.

Currently, `AttackEntityCallback` handles the check with no filter (passes `Entity`), it just checks that you have `TrustLevels.Levels.BASIC` regardless of the entity type. 

If there is sufficient justification for the current behavior then it can be left as is!

### To reproduce

1. Create a claim and spawn a monster in it
2. Transfer it to somebody that isn't you, or `.admin`
3. Try to attack the monster

### Expected behavior

Monsters, at the very least, should be attackable on the spawn roads. Default behavior for other types of claims is probably up for discussion.

### Please confirm

- [X] This is not an exploit

**Comment by Lemmmy** [comment]
@kotahu - I am happy to work on this, but seeking further feedback first.

**Comment by Lemmmy** [comment]
![1 19-entities](https://user-images.githubusercontent.com/858456/212548346-d80cd189-4b4a-47a0-a26f-0c34ef9a7b77.svg)

**Comment by kotahu** [comment]
Allowing players to attack hostile mobs in claims by default would definitely be a good improvement, as the current functionality can be quite frustrating.

The three new claim flags suggested sound good, but stylistically rather than having a flag set by default, I prefer to have a flag that disables the new default behavior.

`monsterDamage` could become something like `protectMonsters`, and allowing attacking monsters could be the default behavior in both admin and user claims.

I can't say I have much experience with datagen/tags, but if you think this would be a good use case then I'm all for it!
