### ISSUE TITLE
Create a command for displaying information about scheduled restarts

### ISSUE THREAD

**Issue by Kan18** [SwitchCraftCC/issues#23]
Potential names:
- `/restartinfo`, `/restartschedule`

Would display time until next restart, the absolute time of the next restart, and information about the restart schedule

**Comment by Lemmmy** [comment]
It turns out [kjob](https://github.com/justwrote/kjob) does not expose the next runtime for the scheduled restart, but we can use it's same internal library, [cron-utils](https://github.com/jmrozanec/cron-utils), to [parse](https://github.com/jmrozanec/cron-utils#:~:text=//%20Create%20a%20parser%20based%20on%20provided%20definition) the cron expression and [calculate the next execution time](https://github.com/jmrozanec/cron-utils#:~:text=ZonedDateTime%20nextExecution%20%3D%20executionTime.nextExecution(now)%3B) for display in the command.
