### ISSUE TITLE
[Suggestion] Bug/Exploit Rewards System

### ISSUE THREAD

**Issue by hugeblank** [SwitchCraftCC/issues#38]
I spent some time thinking about the justification I would have for responsibly reporting an exploit, were it to ever happen. My reasoning ended up being morality, good karma, and understanding the stresses of server administration can be, which is more than enough for me. But for someone else who isn't incentivized by morality, disregards karma, and doesn't care about the difficulty of server admin, keeping exploits under wraps and utilizing it for themselves is far more beneficial. My proposal is to give 250 krist to players who responsibly report exploits. My mind immediately goes to 250 as that's a solid step up from the 100 that a new player gets, and a substantial enough reward that it would likely outweigh any profit that they may get from putting exploited/duped goods on a shop.

I don't mean to say that for every player an exploit rewards system would work, but I think for a majority of them, even those who may put the effort into setting up a shop, it's quite a good deal.

**Comment by Lemmmy** [comment]
At the risk of sounding flippant, I think the "justification" is that you get muted or banned otherwise, depending on the severity of the incident! At least, that's what current precedent has been.

If we source more funding for the master wallet we may be able to look into something like this, but I believe it's a @0x3d6 question.

**Comment by A-Cloud-Ninja** [comment]
I have an accumulated wealth that would otherwise not be put to use. If some verified system is able to be put in place, I can toss like, K50,000 immediately to back some rewards/UBI/etc.

**Comment by umnikos** [comment]
A reward, if big enough, will actually incentivize people to go and hunt for these bugs before they become a problem. Also, "not getting banned" is a rather weird reward to give to someone who just discovered a vulnerability and is disclosing it to you.

**Comment by Lustyn** [comment]
In all honesty, I don't see why incentivizing searching for game exploits is necessary. Bug bounty programs typically exist in circumstances of high stakes where there can be real-world and financial impact to the server and those involved. Both parties in these situations understand there is a mutually beneficial relationship. This isn't so mutual on SwitchCraft.

In-game exploits typically won't cause lasting damage, and ultimately them existing in the wild will just result in someones eventual ban and a small impact on the already quite stagnant economy. It shouldn't be the job of staff to try to protect players from themselves. Fixing these requires time and effort that, frankly, is of not of anyone's interest.

As a small thought experiment, consider the previous iterations of SwitchCraft and how exploits affected those servers long term. On SC1, there existed an exploit known to several players which could directly allow for _spawning in arbitrary items_, and yet even with the existence of admin shops the economy remained afloat and functional for the servers entire lifespan. SC2 had no shortages of dupes, and those diligent enough to find these exploits often were plenty motivated by the cooperation with staff (and other mod developers) to ensure they did not blow up into further problems for the server. Those interested in exploiting these bugs likely would not be exploiting them at a scale that matters, lest they get caught and reprimanded.

These incentive mechanisms really just seem to me like a pipe dream for the few who have more interest in breaking the game rather than actually playing it. Recognizing that you helped (incidentally) prevent a disaster is fine, but asking that you receive something in return is just a [beg bounty](https://www.troyhunt.com/beg-bounties/).

**Comment by hugeblank** [comment]
> Bug bounty programs typically exist in circumstances of high stakes where there can be real-world and financial impact to an organization and those involved.

This is a valid point, but I also think the time input by the staff (Lem) to fix these issues when things go awry is at the very bare minimum worth 250 funny money. Said funny money has no financial or real-world value, much like the bugs themselves. Therefore, in essence, the scale of a program like the one proposed is still worthwhile. If we were sending actual money to players, then yeah I'd totally understand the criticism.

> It shouldn't be the job of staff to try to protect players from themselves.

I'd be inclined to agree but the past 48 hours have proven otherwise...

> Those interested in exploiting these bugs likely would not be exploiting them at a scale that matters, lest they get caught and reprimanded.

That's exactly the problem I'm trying to solve with my proposal. It becomes harder to detect if it's not overtly exploited.

> These incentive mechanisms really just seem to me like a pipe dream for the few who have more interest in breaking the game rather than actually playing it.

Ideally, yeah this would be the case. I'd rather have that than an undisclosed vulnerability!

> Recognizing that you helped (incidentally) prevent a disaster is fine, but asking that you receive something in return is just a [beg bounty](https://www.troyhunt.com/beg-bounties/).

Consider that the admin don't have to come to a conclusion on this proposal in public. And also that we're talking about a valueless currency that only means anything on SC as the reward. *And also that* I'm implying that the time it takes for Lem/staff to address any irresponsibly disclosed exploit is worth 250 krist (kinda insulting!) **And also that** I'm asking for the sake of other players. All I want is more means for krist to be distributed. Especially in ways that take effort, which tragically seems to be the case for exploit reporting (>.> #70). The mere existence of a bug bounty framework would prevent the entire premise of that article (which was "I hate people that fearmonger with 'exploit' reports and expect money in return").

**Comment by Lustyn** [comment]
> This is a valid point, but I also think the time input by the staff (Lem) to fix these issues when things go awry is at the very bare minimum worth 250 funny money

I'm struggling to understand here, are you suggesting that staff are the ones who should be paid Krist? Reporting an exploit is the bare minimum, and actually _fixing_ the exploit requires a significantly larger amount of time. You aren't going to convince any staff member to give you 250 KST for your 10 minutes of writing an exploit report when solving it costs them several hours of their day. This isn't an ethical dilemma on "I need a reason to report this responsibly", the ethical dilemma ended when you agreed to the rules that say you cannot abuse (and should report) exploits.

> I'd be inclined to agree but the past 48 hours have proven otherwise...

Otherwise in what sense? If anything, the irresponsible disclosure is further proof that staff _shouldn't_ have to deal with this and its an error of not reading the many, **MANY** prior warnings. No one is going to say that its your fault for stumbling across an issue, but you don't get free reign to spread it around and break the rules just because you don't agree with whether or not incentive is offered. It's the players job to follow the rules.

> Ideally, yeah this would be the case. I'd rather have that than an undisclosed vulnerability!

Finding exploits is not a means for your game progression, and similarly, opening feature requests is not part of your game progression. You can make Krist by logging in every day and bartering. Offering incentive just encourages players to create extra work for staff--and frankly in most cases I think most players won't be finding the game breaking exploits that matter and result to similarly pointless "beg bounty" scenarios because they see it as the easy way to make quick cash.

> All I want is more means for krist to be distributed. Especially in ways that take effort, which tragically seems to be the case for exploit reporting (>.> https://github.com/SwitchCraftCC/issues/issues/70). The mere existence of a bug bounty framework would prevent the entire premise of that article (which was "I hate people that fearmonger with 'exploit' reports and expect money in return").

Again, this is not a game mechanic so you shouldn't expect it to be a positive means for your progression. Offering bounties in the first place is why people come to expect them for every single little report in the real-world.

**Comment by hugeblank** [comment]
> I'm struggling to understand here, are you suggesting that staff are the ones who should be paid Krist?

I'm not though they deserve it, haha.

> Reporting an exploit is the bare minimum, and actually fixing the exploit requires a significantly larger amount of time. You aren't going to convince any staff member to give you 250 KST for your 10 minutes of writing an exploit report when solving it costs them several hours of their day. 

I can agree with the first part of this. The latter part I'd like to point out that responsibly reporting an exploit allows for that "several hours" to be spread out across a much more relaxed interval, rather than immediately (either through finding out someone is exploiting an issue, or by an irresponsible report.) Of course in both cases the sooner the issue gets fixed the better.

ooh an edit!
Yes, you understand what I was trying to convey.

> If you need incentive to follow the rules, please reconsider how you treat other people and play on a different server.

I have a handful of people that I think could use reading this. 
Also children are surprisingly bad at:
1. following rules
2. considering, let alone reconsidering
3. treating other people *anything* besides poorly.

Given the apparent demographic of children (or adults that act like children) on the server, I'd say a pretty reasonable middle ground is 250 krist. 

> If anything, the irresponsible disclosure is further proof that staff shouldn't have to deal with this and its an error of not reading the many, MANY prior warnings.

I'm confused by what you mean in your initial comment, then:
>>It shouldn't be the job of staff to try to protect players from themselves.

What did you mean by this? What's the point of staff if not to, generally, protect players? 

> opening feature requests is not part of your game progression.

I disagree! #67 was a great suggestion that got implemented very quickly that affected how a system I had made to shower players in krist (plus a promotional message). "game progression" doesn't exactly have a concrete definition in MC, let alone SC. And I don't necessarily see that it's a problem if someone were to make a side hustle out of finding exploits, as long as they're not obnoxious about it to others/staff. Also, looking at the rules, I feel like "beg bounties" loosely break rules 4, 5, and 6. Ideally an addendum to rule 3 along the lines of "don't ask for compensation when reporting an exploit" would be in order, assuming a reward system is put in place. (quick link to the [rules](https://docs.sc3.io/rules.html))

> You can make Krist by logging in every day

You insist that a bug bounty program is not a game mechanic. This isn't one either. It's a reward for joining the game. And I bet it even came around due to a proposal in a similar vein to this one. At least this proposal requires actually doing something actionable and worth a pat on the back for.

**Comment by Lemmmy** [comment]
Work on this will begin today

**Comment by Lemmmy** [comment]
:bug::boom: Thank you for your recent feedback on our exploit reporting process. As suggested by hugeblank in issues#38, we have implemented a new bug bounty system and private exploit reporting form.

Responsibly disclosing exploits via a private process (Google Forms, contacting staff privately) may make you eligible for a bug bounty of at least **500 KST**. If you are eligible, the bug bounty will be paid out when the issue has been fixed and the fix has been deployed to the server.

On the other hand, if you do not follow responsible disclosure process, and irresponsibly disclose an exploit (in public chat, or abusing the exploit for your own gain), you may be muted or banned as per Rule 3.

- For more information on reporting exploits, see: <https://github.com/SwitchCraftCC/issues#reporting-exploits>
- To report an exploit, please use our new form: <https://exploit.sc3.io>
- To report any other bugs, please continue to use our public issue trackers as usual: <https://github.com/SwitchCraftCC/issues>

**If you are ever in any doubt, privately talk to a member of staff first!**

This is the first revision of our new responsible disclosure system, and we may make adjustments to the rules and process in the future. We welcome your feedback on this new system.
