### ISSUE TITLE
CC:T quick settings button not working

### ISSUE THREAD

**Issue by SwitchCraft3** [SwitchCraftCC/issues#42]
### Describe the bug

The CC:Tweaked quick settings button (under the Options menu) does not function

### To reproduce

1. Go to the game menu > Options
2. Click the CC:T button
3. Nothing happens

### Expected behavior

It should show the CC:Tweaked mod settings menu

### Please confirm

- [X] This is not an exploit

**Comment by Lemmmy** [comment]
Shortly before launch, some problems in the forgeconfigapiport updating process resulted in CC's mod settings screen breaking. We worked around this by having a special flag for that button that just opens the config folder instead, but I was under the impression this issue was fixed in CC/forgeconfigapiport. 

You'll notice that CC doesn't have a settings button in ModMenu either, that's why the button does nothing, though it's better than the crash it used to cause instead.

I'll revert back to the behavior of opening the folder for now.
