### ISSUE TITLE
Redstone is broken

### ISSUE THREAD

**Issue by jayjna** [SwitchCraftCC/issues#52]
When using redstone sorting machines sometimes they break allowing more items (the filter item) to pass through than they should breaking the machine.

**Comment by Lemmmy** [comment]
When creating an issue report, please use our [issue template](https://github.com/SwitchCraftCC/issues/issues/new?assignees=&labels=&template=bug_report.yaml) - it saves us having to ask all the mundane questions and speeds things up for everybody.

This sounds like a niche use case with no useful explanation provided. Do you have any specific reproduction steps? Is it definitely a SwitchCraft issue and not a vanilla issue? "Sometimes" is quite vague - are you able to succintly demonstrate the issue, perhaps with a video? Are you sure it is not a visual/network desync?

SwitchCraft does not touch any redstone code itself, but it does use a number of optimization mods on the server, including but not limited to: [Lithium](https://modrinth.com/mod/lithium), [FerriteCore](https://modrinth.com/mod/ferrite-core), [Krypton](https://modrinth.com/mod/krypton). Are you able to reproduce the issue using just Fabric and these mods?

**Comment by Lemmmy** [comment]
Obligatory: this is a ComputerCraft server, perhaps sorting is a task better suited to CC ;)

**Comment by jayjna** [comment]
This seems to be a switchcraft issue, on other vanilla single player and multiplayer worlds and spigot and paper spigot servers this issue doesn't happen. The only way to recreate the issue would be to create a redstone sorting machine and wait I believe it's when the server drops in TPS but I don't know. A redstone sorting machine works by a specific amount of items inside a hopper which triggers a comparator which unlocks the Hopper below and allows that specific item to pass through but it seems like the Hopper isn't being locked fast enough which is allowing more items than it should to pass through the locked Hopper

**Comment by Lemmmy** [comment]
Thanks for your feedback on this. I haven't been able to find anything specific in SwitchCraft's mods that would contribute to breaking your specific use case. Since this is a CC:T server, sorting machines are probably better implemented by a computer rather than redstone.

I will keep an ear to the ground for redstone-related issues, so if you have a more specific example (with coordinates, screenshots, videos, or at the very least detailed reproduction steps) please do open a new issue with our issue template!
