### ISSUE TITLE
<Invalid>

### ISSUE THREAD

**Issue by stealthy-coder** [SwitchCraftCC/issues#62]
### Describe the bug

in chat when you say anyhing starting with '@', '#', ':', 'a', 't' surrounded by '\<\>' it replaces the word with \<Invalid\>

### Please confirm

- [X] This is not an exploit

**Comment by Lemmmy** [comment]
This pattern catches potential Discord nodes early:

https://github.com/SwitchCraftCC/SwitchCraft3/blob/2a288a87f1283885ee5155f199df0a84ff259e4c/sc-utils/src/main/kotlin/io/sc3/utils/markdown/MarkdownParser.kt#L78

And then falls-through here to render `invalid(content)`:

https://github.com/SwitchCraftCC/SwitchCraft3/blob/2a288a87f1283885ee5155f199df0a84ff259e4c/sc-utils/src/main/kotlin/io/sc3/utils/markdown/discord/DiscordMcTextNodeRenderer.kt#L102

Instead of calling `invalid`, could probably just write the original content.
